- name: Create Instance
  hosts: localhost
  tasks:
    - name: start an instance with metadata options
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        image_id: ami-03265a0778a880afb
        tags:
          Name: ansible-test
